// benchmark-todo/react-todo/src/App.jsx
import { useState } from 'react'
import TodoItem from './components/TodoItem'

function App() {
  const [tasks, setTasks] = useState([])
  const [taskName, setTaskName] = useState('')
  const [priority, setPriority] = useState('medium')
  const [editingId, setEditingId] = useState(null)
  const [benchmarkResults, setBenchmarkResults] = useState(null)
  const [running, setRunning] = useState(false)

  const addTask = () => {
    if (!taskName.trim()) return
    const newTask = {
      id: Date.now(),
      name: taskName,
      priority,
    }
    setTasks(prev => [...prev, newTask])
    setTaskName('')
    setPriority('medium')
  }

  const deleteTask = (id) => {
    setTasks(prev => prev.filter(t => t.id !== id))
  }

  const startEdit = (id) => setEditingId(id)
  const cancelEdit = () => setEditingId(null)

  const updateTask = (id, name, priority) => {
    setTasks(prev => prev.map(t => (t.id === id ? { ...t, name, priority } : t)))
    setEditingId(null)
  }

  const bench = async (label, fn) => {
    const start = performance.now()
    await fn()
    await new Promise(r => requestAnimationFrame(r))
    const end = performance.now()
    return { label, time: +(end - start).toFixed(2) }
  }

  const generateTasks = (count) =>
    Array.from({ length: count }, (_, i) => ({
      id: i,
      name: `Task ${i + 1}`,
      priority: ['low', 'medium', 'high'][i % 3],
    }))

  const runBenchmarks = async () => {
    setRunning(true)
    setBenchmarkResults(null)
    const rows = []

    for (const count of [100, 500, 1000]) {
      const r = await bench(`Render ${count} tasks`, async () => {
        const t = generateTasks(count)
        setTasks(t)
      })
      rows.push(r)
    }

    const r = await bench('Update 50 tasks', async () => {
      setTasks(prev => prev.map((t, i) => (i < 50 ? { ...t, name: `${t.name} ★` } : t)))
    })
    rows.push(r)

    const r2 = await bench('Delete 50 tasks', async () => {
      setTasks(prev => prev.slice(50))
    })
    rows.push(r2)

    setBenchmarkResults(rows)
    setRunning(false)
  }

  return (
    <div className="app">
      <header>
        <h1>React Todo — Benchmark</h1>
        <p>React {React.version} — Virtual DOM with diffing reconciliation</p>
      </header>

      <section className="controls">
        <input
          placeholder="Task name"
          value={taskName}
          onChange={e => setTaskName(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && addTask()}
        />
        <select value={priority} onChange={e => setPriority(e.target.value)}>
          <option value="low">Low</option>
          <option value="medium">Medium</option>
          <option value="high">High</option>
        </select>
        <button onClick={addTask}>Add Task</button>
      </section>

      <section className="bench-bar">
        <button className="btn-bench" onClick={runBenchmarks} disabled={running}>
          {running ? 'Running benchmarks…' : 'Run Benchmarks'}
        </button>
        <span className="task-count">{tasks.length} tasks</span>
      </section>

      {benchmarkResults && (
        <section className="results">
          <h2>Benchmark Results (ms)</h2>
          <table>
            <thead>
              <tr><th>Operation</th><th>Time (ms)</th></tr>
            </thead>
            <tbody>
              {benchmarkResults.map((r, i) => (
                <tr key={i}><td>{r.label}</td><td>{r.time}</td></tr>
              ))}
            </tbody>
          </table>
        </section>
      )}

      <ul className="todo-list">
        {tasks.map(t => (
          <TodoItem
            key={t.id}
            task={t}
            isEditing={editingId === t.id}
            onStartEdit={() => startEdit(t.id)}
            onCancelEdit={cancelEdit}
            onUpdate={updateTask}
            onDelete={deleteTask}
          />
        ))}
      </ul>
    </div>
  )
}

export default App

// benchmark-todo/angular-todo/src/app/app.component.ts
import { Component } from '@angular/core'

interface Task {
  id: number
  name: string
  priority: string
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Angular Todo — Benchmark'
  sub = 'Angular 17 — Change detection with Zone.js & directives'

  tasks: Task[] = []
  taskName = ''
  priority = 'medium'
  editingId: number | null = null
  editName = ''
  editPriority = 'medium'

  results: { label: string; time: number }[] = []
  running = false

  addTask() {
    if (!this.taskName.trim()) return
    this.tasks.push({
      id: Date.now(),
      name: this.taskName,
      priority: this.priority,
    })
    this.taskName = ''
    this.priority = 'medium'
  }

  deleteTask(id: number) {
    this.tasks = this.tasks.filter(t => t.id !== id)
  }

  startEdit(task: Task) {
    this.editingId = task.id
    this.editName = task.name
    this.editPriority = task.priority
  }

  cancelEdit() {
    this.editingId = null
  }

  saveEdit(id: number) {
    if (!this.editName.trim()) return
    const idx = this.tasks.findIndex(t => t.id === id)
    if (idx !== -1) {
      this.tasks[idx] = { ...this.tasks[idx], name: this.editName, priority: this.editPriority }
      this.tasks = [...this.tasks]
    }
    this.editingId = null
  }

  private generateTasks(count: number): Task[] {
    return Array.from({ length: count }, (_, i) => ({
      id: i,
      name: `Task ${i + 1}`,
      priority: ['low', 'medium', 'high'][i % 3],
    }))
  }

  private async bench(label: string, fn: () => void): Promise<{ label: string; time: number }> {
    const start = performance.now()
    fn()
    await new Promise(r => setTimeout(r, 0))
    const end = performance.now()
    return { label, time: +((end - start) * 10).toFixed(2) }
  }

  async runBenchmarks() {
    this.running = true
    this.results = []
    const rows: { label: string; time: number }[] = []

    for (const count of [100, 500, 1000]) {
      const r = await this.bench(`Render ${count} tasks`, () => {
        this.tasks = this.generateTasks(count)
      })
      rows.push(r)
    }

    const r = await this.bench('Update 50 tasks', () => {
      this.tasks = this.tasks.map((t, i) =>
        i < 50 ? { ...t, name: t.name + ' ★' } : t
      )
    })
    rows.push(r)

    const r2 = await this.bench('Delete 50 tasks', () => {
      this.tasks = this.tasks.slice(50)
    })
    rows.push(r2)

    this.results = rows
    this.running = false
  }
}

<div class="app">
  <header>
    <h1>{{ title }}</h1>
    <p>{{ sub }}</p>
  </header>

  <section class="controls">
    <input [(ngModel)]="taskName" placeholder="Task name" (keydown.enter)="addTask()" />
    <select [(ngModel)]="priority">
      <option value="low">Low</option>
      <option value="medium">Medium</option>
      <option value="high">High</option>
    </select>
    <button (click)="addTask()">Add Task</button>
  </section>

  <section class="bench-bar">
    <button class="btn-bench" (click)="runBenchmarks()" [disabled]="running">
      {{ running ? 'Running benchmarks…' : 'Run Benchmarks' }}
    </button>
    <span class="task-count">{{ tasks.length }} tasks</span>
  </section>

  <section class="results" *ngIf="results.length > 0">
    <h2>Benchmark Results (ms)</h2>
    <table>
      <thead><tr><th>Operation</th><th>Time (ms)</th></tr></thead>
      <tbody>
        <tr *ngFor="let r of results">
          <td>{{ r.label }}</td>
          <td>{{ r.time }}</td>
        </tr>
      </tbody>
    </table>
  </section>

  <ul class="todo-list">
    <li class="todo-item" *ngFor="let task of tasks">
      <ng-container *ngIf="editingId === task.id; else display">
        <input [(ngModel)]="editName" />
        <select [(ngModel)]="editPriority">
          <option value="low">Low</option>
          <option value="medium">Medium</option>
          <option value="high">High</option>
        </select>
        <button class="save" (click)="saveEdit(task.id)">Save</button>
        <button class="cancel" (click)="cancelEdit()">Cancel</button>
      </ng-container>
      <ng-template #display>
        <span class="task-name">{{ task.name }}</span>
        <span class="badge" [style.background]="task.priority === 'low' ? '#4CAF50' : task.priority === 'medium' ? '#FF9800' : '#f44336'">
          {{ task.priority }}
        </span>
        <div class="actions">
          <button class="edit" (click)="startEdit(task)">✎</button>
          <button class="delete" (click)="deleteTask(task.id)">✕</button>
        </div>
      </ng-template>
    </li>
  </ul>
</div>
